# Generated by Django 5.0.4 on 2024-04-24 01:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
        ("movies_orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="marker",
            field=models.ManyToManyField(
                related_name="marked_movie",
                through="movies_orders.MovieOrder",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
